POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"devbapidey@gmail.com"
}

###
POST http://localhost:3000/profile
Content-Type: application/json

{
    "email":"devbapidey@gmail.com",
    "name":"A Student"
}